name: Daily EGX Stock Update

on:
  schedule:
    - cron: "30 13 * * *"  # Runs daily at 13:30 UTC (15:30 Cairo)
  workflow_dispatch:  # Allows manual run

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas beautifulsoup4 requests openpyxl

      - name: Run scraper
        run: python egx_scraper.py

      - name: Commit CSV
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "EGX Bot"
          git add egx_data.csv
          git commit -m "Auto-update EGX stock data"
          git push
